server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidosdb
    username: postgres
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
